### ISSUE TITLE
关于CI目前的发现

### ISSUE THREAD

**Issue by chanchancl** [skywind3000/GONGLUE#4]
目前看起来，这个 hhc 在github actions的 windows runner下，运行会有问题

我做了一些测试：

1. 只使用GONGLUE目录下的其中一个游戏类型，hhc 至少有输出了，但是和本地输出不同，路径包含中文的都显示H5003错误并且生成的chm无法工作

本地生成的是正常可工作的，CI生成的就有点问题

本地生成的： [GONGLUE local.zip](https://github.com/skywind3000/GONGLUE/files/15457178/GONGLUE.local.zip)
CI生成的：[GONGLUE CI.zip](https://github.com/chanchancl/goneluetest/actions/runs/9252148692/artifacts/1540301750)

CI Build : [测试一个目录](https://github.com/chanchancl/goneluetest/actions/runs/9251014067/job/25445644844#step:8:30)

```
HHC5003: Error: Compilation failed while compiling html\���� ������ս����SLG\X-COM3(�ĸ���--��ʾ¼).html.
HHC5003: Error: Compilation failed while compiling html\���� ������ս����SLG\������ʿ.html.
HHC5003: Error: Compilation failed while compiling html\���� ������ս����SLG\�ܲٴ�.html.
HHC5003: Error: Compilation failed while compiling html\���� ������ս����SLG\��ʱ��Ӣ�۴�˵.html.
```
对应的应该是
```
html\攻略 策略与战棋类SLG\X-COM3(幽浮Ⅲ--启示录).html
html\攻略 策略与战棋类SLG\保皇骑士.html
html\攻略 策略与战棋类SLG\曹操传.html
html\攻略 策略与战棋类SLG\超时空英雄传说.html
```

2. 目前如果某个攻略路径是纯英文的，就可以包含进去，一旦出现中文就不行，生成的chm里路径是有的，但是打开显示找不到此页

尝试使用 chcp, Set-Culture, 等解决，但没效果，这个runner的默认chcp是 65001

可以在这里查看其中的一些build： [Link](https://github.com/chanchancl/goneluetest/actions/workflows/build.yml)

![image](https://github.com/skywind3000/GONGLUE/assets/11457297/62ec4275-4d08-4f3e-9b5f-b6756460114f)

![image](https://github.com/skywind3000/GONGLUE/assets/11457297/b7208345-9efb-49da-9078-83e3a3f10875)

3. 在本地用chcp吧代码页切到 65001，编译的时候输出的内容是虽然是乱码，但生成的文件是没问题的。但是反过来在runner上把 chcp改为 936 就没用，我猜测可能和系统原本的 语言区域设置相关

[GONGLUE local with 65001.zip](https://github.com/skywind3000/GONGLUE/files/15457289/GONGLUE.local.with.65001.zip)

![image](https://github.com/skywind3000/GONGLUE/assets/11457297/26bd0d32-0040-4b1a-b9fc-ca3dd5a6de59)

**Comment by skywind3000** [comment]
我已经改了，启用 Html Help Workshop，改用开源的 chmcmd 工具（来自 Free Pascal），
然后重写了 chm 生成脚本，避免任何中文文件名，全部用序号编号，现在应该是 OK 的。

https://github.com/skywind3000/GONGLUE/actions/runs/9257096389/job/25464500463

但是我还不知道怎么把这个脚本改成 release 的时候自动上传，其它时候不工作，以及输出按照：

- GONGLUE-{日期}.chm
- GONGLUE-{日期}.epub

或者：

- GONGLUE-{版本号}.chm
- GONGLUE-{版本号}.chm

重命名。

**Comment by chanchancl** [comment]
可以这样，根目录放一个 version 文件，里面写当前版本，例如  1.2.5

然后在一个step中生成所有要用到的信息并加到环境变量里 [Link](https://github.com/chanchancl/goneluetest/blob/master/.github/workflows/build.yml#L49)

例如：
```
Version: 1.2.5
Release date: 20240526
CHM file name: GONGLUE-20240526.chm
EPUB file name: GONGLUE-20240526.epub
```

使用下面这段来把每次编译的文件上传到这次build的 artifact 用于调试之类的
```
- name: Upload CHM file for test
  uses: actions/upload-artifact@v3
  with:
    name: ${{ env.CHM_NAME }}
    path: build/GONGLUE.chm

- name: Upload EPUB file for test
  uses: actions/upload-artifact@v3
  with:
    name: ${{ env.EPUB_NAME }}
    path: build/GONGLUE.epub
```


在创建release时，使用 ${{ env::VERSION }} 作为tag，如果version不修改，在创建release的时候就会失败

这样，平时的push会编译CHM 和 EPUB上传到 artifact，但是不release，只有修改version时才会release

最后使用上面生成的变量上传文件到release即可 Upload CHM file to release

可以参考这两个build
[build1 release success](https://github.com/chanchancl/goneluetest/actions/runs/9257543687/job/25465893268#step:13:1)
[build2 release failed because tag already exist](https://github.com/chanchancl/goneluetest/actions/runs/9257629933/job/25466171895#step:13:16)

总的 CI 文件： [Link](https://github.com/chanchancl/goneluetest/blob/master/.github/workflows/build.yml)
